-- Add profile completion fields to users table
ALTER TABLE users ADD COLUMN phone VARCHAR(30) NULL ;
ALTER TABLE users ADD COLUMN state VARCHAR(100) NULL ;
ALTER TABLE users ADD COLUMN city VARCHAR(100) NULL ;
ALTER TABLE users ADD COLUMN pincode VARCHAR(10) NULL ;
ALTER TABLE users ADD COLUMN experience INT NULL ;
ALTER TABLE users ADD COLUMN about TEXT NULL ;
ALTER TABLE users ADD COLUMN skills TEXT NULL ;
ALTER TABLE users ADD COLUMN work_type VARCHAR(255) NULL ;
ALTER TABLE users ADD COLUMN profile_completed SMALLINT NOT NULL DEFAULT 0 ;
